name: Deploy to gcloud

on:
  push:
    branches: [master]

jobs:
  changes:
    name: changes
    runs-on: ubuntu-latest
    outputs:
      cmd: ${{ steps.filter.outputs.cmd }}
      cmd_files: ${{ steps.filter.outputs.cmd_files }}
      pkg: ${{ steps.filter.outputs.pkg }}
      pkg_files: ${{ steps.filter.outputs.pkg_files }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Path Filter task and Execute
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            pkg:
              - 'pkg/**'
            cmd:
              - 'filtertest/**'

  check-pkg-dependancies:
    needs: changes
    if: ${{ needs.changes.outputs.pkg == 'false' }}
    name: Check dependancies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Verify dependancy versions
        env:
          TEST: ${{ secrets.TEST }}
        shell: bash
        run: |
          echo "hello world pkg update"
          echo $TEST

  deploy-to-cloud:
    needs: changes
    if: ${{ needs.changes.outputs.cmd == 'true' }}
    name: deploy to gcloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #- name: Setup gcloud actions
      #uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      #with:
      #service_account_key: ${{ secrets.PROD_GCLOUD_AUTH }}
      #project_id: ${{ secrets.PROD_GCP_PROJECT_ID }}

      - name: Deploy modified functions
        shell: bash
        run: ./ci/deploy.sh ${{ needs.changes.outputs.cmd_files }}
