name: Deploy to gcloud

on:
  push:
    branches:
      - master

jobs:
  changes:
    name: changes
    runs-on: ubuntu-latest
    outputs:
      cmd: ${{ steps.filter.outputs.cmd }}
      cmd_files: ${{ steps.filter.outputs.cmd_files }}
      pkg: ${{ steps.filter.outputs.pkg }}
      pkg_files: ${{ steps.filter.outputs.pkg_files }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Path Filter task and Execute
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            pkg:
              - 'pkg/**'
            cmd:
              - 'filtertest/**'

  check-pkg-dependancies:
    needs: changes
    name: Check dependancies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Verify dependancy versions
        shell: bash
        run: |
          echo "hello world pkg update"
          echo $TEST

  deploy-to-cloud:
    needs: [changes, check-pkg-dependancies]
    if: ${{ needs.changes.outputs.cmd == 'true' }}
    name: deploy to gcloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: Deploy modified functions
        shell: bash
        run: ./ci/deploy.sh ${{ needs.changes.outputs.cmd_files }}
